const { Animal } = require("../models");

const animalData = [
  {
    farm_id: 1,
    name: "Cowboy",
    type: "cow",
    breed: "Highland Cattle",
    food_organic: 150,
    food_manufactured: 100,
    output: "meat",
  },
  {
    farm_id: 2,
    name: "Brutis",
    type: "chicken",
    breed: "Ameraucana",
    food_organic: 150,
    food_manufactured: 100,
    output: "eggs",
  },
  {
    farm_id: 3,
    name: "Wilbur",
    type: "pig",
    breed: "Babe",
    food_organic: 150,
    food_manufactured: 100,
    output: "meat",
  },
  {
    farm_id: 4,
    name: "Amy",
    type: "squid",
    food_organic: 150,
    food_manufactured: 100,
    output: "ink",
  },
  {
    farm_id: 5,
    name: "Sky",
    type: "cow",
    breed: "Milk cow",
    food_organic: 150,
    food_manufactured: 100,
    output: "milk",
  },
  {
    farm_id: 5,
    name: "doby",
    type: "cow",
    breed: "Milk cow",
    food_organic: 150,
    food_manufactured: 100,
    output: "milk",
  },
  {
    farm_id: 5,
    name: "velma",
    type: "cow",
    breed: "Milk cow",
    food_organic: 150,
    food_manufactured: 100,
    output: "milk",
  },
  {
    farm_id: 5,
    name: "raisin",
    type: "chicken",
    breed: "egg chicken",
    food_organic: 50,
    food_manufactured: 20,
    output: "egg",
  },
  {
    farm_id: 5,
    name: "grape",
    type: "chicken",
    breed: "egg chicken",
    food_organic: 50,
    food_manufactured: 20,
    output: "egg",
  },

  {
    farm_id: 5,
    name: "bessie",
    type: "cow",
    breed: "cattle",
    food_organic: 110,
    food_manufactured: 55,
    output: "meat",
  },
  {
    farm_id: 5,
    name: "agatha",
    type: "cow",
    breed: "cattle",
    food_organic: 100,
    food_manufactured: 60,
    output: "meat",
  },
  {
    farm_id: 5,
    name: "tim",
    type: "chicken",
    breed: "silkie",
    food_organic: 50,
    food_manufactured: 20,
    output: "egg",
  },
  {
    farm_id: 5,
    name: "sufi",
    type: "chicken",
    breed: "marans",
    food_organic: 50,
    food_manufactured: 20,
    output: "egg",
  },
  {
    farm_id: 5,
    name: "matt",
    type: "pig",
    breed: "duroc",
    food_organic: 130,
    food_manufactured: 50,
    output: "meat",
  },
  {
    farm_id: 5,
    name: "luke",
    type: "pig",
    breed: "mangalica",
    food_organic: 125,
    food_manufactured: 55,
    output: "meat",
  },
  {
    farm_id: 5,
    name: "sean",
    type: "sheep",
    breed: "dorper",
    food_organic: 50,
    food_manufactured: 35,
    output: "wool",
  },
  {
    farm_id: 5,
    name: "greg",
    type: "sheep",
    breed: "awassi",
    food_organic: 60,
    food_manufactured: 30,
    output: "wool",
  },
  {
    farm_id: 5,
    name: "ron",
    type: "horse",
    breed: "friesian",
    food_organic: 150,
    food_manufactured: 75,
    output: "labor",
  },
  {
    farm_id: 5,
    name: "meghan",
    type: "horse",
    breed: "mustang",
    food_organic: 120,
    food_manufactured: 60,
    output: "labor",
  },

];

const animalSeeds = () => Animal.bulkCreate(animalData);

module.exports = animalSeeds;
